### ISSUE TITLE
Rails 4 - attr_accessible

### ISSUE THREAD

**Issue by kurtisnelson** [thirst/glass-rails#3]
``` ruby
be bin/rails g glass:install                                                                                    master
/Users/kurt/.rvm/gems/ruby-2.0.0-p247/gems/activemodel-4.0.0/lib/active_model/deprecated_mass_assignment_security.rb:14:in `attr_accessible': `attr_accessible` is extracted out of Rails into a gem. Please use new recommended protection model for params(strong_parameters) or add `protected_attributes` to your Gemfile to use old one. (RuntimeError)
        from /Users/kurt/.rvm/gems/ruby-2.0.0-p247/gems/glass-rails-0.1.5/lib/glass/timeline_item.rb:18:in `<class:TimelineItem>'
        from /Users/kurt/.rvm/gems/ruby-2.0.0-p247/gems/glass-rails-0.1.5/lib/glass/timeline_item.rb:8:in `<module:Glass>'
        from /Users/kurt/.rvm/gems/ruby-2.0.0-p247/gems/glass-rails-0.1.5/lib/glass/timeline_item.rb:7:in `<top (required)>'
        from /Users/kurt/.rvm/gems/ruby-2.0.0-p247/gems/activesupport-4.0.0/lib/active_support/dependencies.rb:228:in `require'
        from /Users/kurt/.rvm/gems/ruby-2.0.0-p247/gems/activesupport-4.0.0/lib/active_support/dependencies.rb:228:in `block in require'
        from /Users/kurt/.rvm/gems/ruby-2.0.0-p247/gems/activesupport-4.0.0/lib/active_support/dependencies.rb:213:in `load_dependency'
        from /Users/kurt/.rvm/gems/ruby-2.0.0-p247/gems/activesupport-4.0.0/lib/active_support/dependencies.rb:228:in `require'
        from /Users/kurt/.rvm/gems/ruby-2.0.0-p247/gems/glass-rails-0.1.5/lib/glass-rails.rb:3:in `<top (required)>'
        from /Users/kurt/.rvm/gems/ruby-2.0.0-p247/gems/bundler-1.3.5/lib/bundler/runtime.rb:72:in `require'
        from /Users/kurt/.rvm/gems/ruby-2.0.0-p247/gems/bundler-1.3.5/lib/bundler/runtime.rb:72:in `block (2 levels) in require'
        from /Users/kurt/.rvm/gems/ruby-2.0.0-p247/gems/bundler-1.3.5/lib/bundler/runtime.rb:70:in `each'
        from /Users/kurt/.rvm/gems/ruby-2.0.0-p247/gems/bundler-1.3.5/lib/bundler/runtime.rb:70:in `block in require'
        from /Users/kurt/.rvm/gems/ruby-2.0.0-p247/gems/bundler-1.3.5/lib/bundler/runtime.rb:59:in `each'
        from /Users/kurt/.rvm/gems/ruby-2.0.0-p247/gems/bundler-1.3.5/lib/bundler/runtime.rb:59:in `require'
        from /Users/kurt/.rvm/gems/ruby-2.0.0-p247/gems/bundler-1.3.5/lib/bundler.rb:132:in `require'
        from /Users/kurt/Workspace/glass-fun/config/application.rb:12:in `<top (required)>'
        from /Users/kurt/.rvm/gems/ruby-2.0.0-p247/gems/railties-4.0.0/lib/rails/commands.rb:44:in `require'
        from /Users/kurt/.rvm/gems/ruby-2.0.0-p247/gems/railties-4.0.0/lib/rails/commands.rb:44:in `<top (required)>'
        from bin/rails:4:in `require'
        from bin/rails:4:in `<main>'
```

**Comment by kurtisnelson** [comment]
Fixed over in kurtisnelson/glass-rails@af72b12a8342f5c7a7f251089438570c7dddb4cf
